services:
  instruction_service:
    build:
      context: ./backend/instruction_service
      dockerfile: Dockerfile
    image: instruction_service:latest
    container_name: instruction_service
    restart: unless-stopped
    ports:
      - "${PORT_INSTRUCTION_SERVICE}:${PORT_INSTRUCTION_SERVICE}"
    command: ["--port", "${PORT_INSTRUCTION_SERVICE}"]
    networks:
      - services

  simulate_service:
    build:
      context: ./backend/simulate_service
      dockerfile: Dockerfile
    image: simulate_service:latest
    container_name: simulate_service
    restart: unless-stopped
    ports:
      - "${PORT_SIMULATE_SERVICE}:${PORT_SIMULATE_SERVICE}"
    command: ["--port", "${PORT_SIMULATE_SERVICE}"]
    networks:
      - services

  graph_service:
    build:
      context: ./backend/graph_service
      dockerfile: Dockerfile
    image: graph_service:latest
    container_name: graph_service
    restart: unless-stopped
    ports:
      - "${PORT_GRAPH_SERVICE}:${PORT_GRAPH_SERVICE}"
    command: ["--port", "${PORT_GRAPH_SERVICE}"]
    networks:
      - services

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${PORT_BFF}:${PORT_BFF}"
    command: []
    networks:
      - services

networks:
  services:
    driver: bridge
