export const uArchOptions = [
    "Haswell",
    "Broadwell",
    "Skylake",
    "Skylake (with AVX-512)",
    "Cascade Lake",
    "Cooper Lake",
    "Ice Lake (client)",
    "Ice Lake (server)",
    "Tiger Lake",
    "Rocket Lake",
    "Alder Lake",
    "Arrow Lake",
    "Lunar Lake",
    "AMD Bobcat (Family 14th)",
    "AMD Bulldozer (Family 15th)",
    "AMD Jaguar (Family 16th)",
    "AMD Zen 1",
    "AMD Zen 2",
    "AMD Zen 3",
    "AMD Zen 4",
    "AMD Zen 5",
    "AMD Zen 6",
];

export const cpuByDisplayName: Record<string, string> = {
    "Haswell": "haswell",
    "Broadwell": "broadwell",
    "Skylake": "skylake",
    "Skylake (with AVX-512)": "skylake-avx512",
    "Cascade Lake": "cascadelake",
    "Cooper Lake": "cooperlake",
    "Ice Lake (client)": "icelake-client",
    "Ice Lake (server)": "icelake-server",
    "Tiger Lake": "tigerlake",
    "Rocket Lake": "rocketlake",
    "Alder Lake": "alderlake",
    "Arrow Lake": "arrowlake",
    "Lunar Lake": "lunarlake",
    "AMD Bobcat (Family 14th)": "btver1",
    "AMD Bulldozer (Family 15th)": "bdver1",
    "AMD Jaguar (Family 16th)": "btver2",
    "AMD Zen 1": "znver1",
    "AMD Zen 2": "znver2",
    "AMD Zen 3": "znver3",
    "AMD Zen 4": "znver4",
    "AMD Zen 5": "znver5",
    "AMD Zen 6": "znver6",
};

export const compilers = ["gcc 13.2", "clang 22.0"]; // TODO: finish
