import { Node } from "./components/GraphNode";
import { TimelineEntry } from "./components/SimViewTimeline";
import { InstructionInfo } from "./components/SimViewInstructions";
import { ArchitectureInfo } from "./components/SimViewResources";

export const nodes: Node[] = [
    {
        id: "L1",
        label: "L1",
        instructions: ["test edi, edi", "js L4"],
        edgesOut: [
            { to: "L2", fallthrough: true, conditional: true, taken: false },
            { to: "L4", conditional: true, taken: true },
        ],
    },
    {
        id: "L2",
        label: "L2",
        instructions: ["mov eax, 1", "mov edx, 1", "jmp L3"],
        edgesOut: [{ to: "L3" }],
    },
    {
        id: "L5",
        label: "L5",
        instructions: ["mov eax, ecx"],
        edgesOut: [{ to: "L3", fallthrough: true }],
    },
    {
        id: "L3",
        label: "L3",
        instructions: [
            "sub edi, 1",
            "lea ecx, [rdx+rax]",
            "mov edx, eax",
            "cmp edi, -1",
            "jne L5",
        ],
        edgesOut: [
            { to: "L5", conditional: true, taken: true },
            { to: "L6", conditional: true, taken: false },
        ],
    },
    {
        id: "L4",
        label: "L4",
        instructions: ["mov eax, 1", "ret"],
        edgesOut: [],
    },
    {
        id: "L6",
        label: "L6",
        instructions: ["mov eax, ecx", "ret"],
        edgesOut: [],
    },
];

export const defaultCppContent = `int fib(int n) {
    int prev = 1, current = 1;
    for (; n >= 0; --n) {
        int tmp = prev + current;
        prev = current;
        current = tmp;
    }
    return current;
}`;

export const defaultAsmContent = `L1:
  movb $5, %ah
  movb $5, %al
  movl $6, %eax
  movb $6, %al
  movb $7, %ah
  mov eax, dword ptr [rdi + 8 * rbx]
  movb $8, %ah
  movb $8, %al
  decl %ecx
  jne .loop`;

export const haswell: ArchitectureInfo = {
    name: "Haswell",
    dispatchWidth: 4,
    resources: [
        "HWDivider",
        "HWFPDivider",
        "HWPort0",
        "HWPort1",
        "HWPort2",
        "HWPort3",
        "HWPort4",
        "HWPort5",
        "HWPort6",
        "HWPort7",
    ],
};

export const generalInfo = {
    iterations: 200,
    instructions: 2000,
    totalCycles: 610,
    totalMicroOps: 2400,
    microOpsPerCycle: 3.93,
    ipc: 3.28,
    blockRThroughput: 3.0,
};

export const instructions = [
    "movb $5, %ah",
    "movb $5, %al",
    "movl $6, %eax",
    "movb $6, %al",
    "movb $7, %ah",
    "mov eax, dword ptr [rdi + 8 * rbx]",
    "movb $8, %ah",
    "movb $8, %al",
    "decl %ecx",
    "jne .loop",
];

export const instructionInfo: InstructionInfo[] = [
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.25,
        mayLoad: false,
        mayStore: false,
        sideFx: false,
    },
    {
        uOps: 3,
        latency: 7,
        rThroughput: 1.0,
        mayLoad: true,
        mayStore: true,
        sideFx: false,
    },
    {
        uOps: 1,
        latency: 1,
        rThroughput: 0.5,
        mayLoad: false,
        mayStore: false,
        sideFx: true,
    },
];

export const resourcePressure: number[][] = [
    [0, 0, 0, 0.01, 0, 0, 0, 0.5, 0.5, 0],
    [0, 0, 0.01, 0.5, 0, 0, 0, 0.5, 0, 0],
    [0, 0, 0.01, 0.5, 0, 0, 0, 0, 0.5, 0],
    [0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.01, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0.01, 0.5, 0],
    [0, 0, 0.5, 0.01, 0, 0, 0, 0.5, 0, 0],
    [0, 0, 0.01, 0.5, 0, 0, 0, 0, 0.5, 0],
    [0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.01, 0],
    [0, 0, 0, 0.5, 0.67, 0.67, 1.0, 0.01, 0.5, 0.67],
    [0, 0, 1.0, 0, 0, 0, 0, 0, 0.01, 0],
];

export const timelineEntries: TimelineEntry[] = [
    // Iteration 0
    {
        iteration: 0,
        instrIndex: 0,
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 1,
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 2,
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 3,
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 4,
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 5,
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 6,
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 7,
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 8,
        dispatchCycles: [1],
        execCycles: [2, 3, 4, 5, 6, 7, 8],
        execEndCycles: [9],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 9,
        dispatchCycles: [1],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [11],
        waitQueueCycles: [2, 3, 4, 5, 6, 7, 8],
        waitRetireCycles: [],
    },
    // Iteration 1
    {
        iteration: 1,
        instrIndex: 0,
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 1,
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 2,
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 3,
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 4,
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 5,
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 6,
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 7,
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 8,
        dispatchCycles: [4],
        execCycles: [5, 6, 7, 8, 9, 10, 11],
        execEndCycles: [12],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 1,
        instrIndex: 9,
        dispatchCycles: [4],
        execCycles: [12],
        execEndCycles: [13],
        retireCycles: [14],
        waitQueueCycles: [5, 6, 7, 8, 9, 10, 11],
        waitRetireCycles: [],
    },
    // Iteration 2
    {
        iteration: 2,
        instrIndex: 0,
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 1,
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 2,
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 3,
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 4,
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 5,
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 6,
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 7,
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 8,
        dispatchCycles: [7],
        execCycles: [8, 9, 10, 11, 12, 13, 14],
        execEndCycles: [15],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 2,
        instrIndex: 9,
        dispatchCycles: [7],
        execCycles: [15],
        execEndCycles: [16],
        retireCycles: [17],
        waitQueueCycles: [8, 9, 10, 11, 12, 13, 14],
        waitRetireCycles: [],
    },
    // Iteration 3
    {
        iteration: 3,
        instrIndex: 0,
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 1,
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 2,
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 3,
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 4,
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 5,
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 6,
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 7,
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 8,
        dispatchCycles: [10],
        execCycles: [11, 12, 13, 14, 15, 16, 17],
        execEndCycles: [18],
        retireCycles: [19],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 3,
        instrIndex: 9,
        dispatchCycles: [10],
        execCycles: [18],
        execEndCycles: [19],
        retireCycles: [20],
        waitQueueCycles: [11, 12, 13, 14, 15, 16, 17],
        waitRetireCycles: [],
    },
];
