import { Node, TimelineEntry } from "./types";

export const nodes: Node[] = [
    {
        id: "L1",
        label: "L1",
        instructions: ["test edi, edi", "js L4"],
        edgesOut: [
            { to: "L2", fallthrough: true, conditional: true, taken: false },
            { to: "L4", conditional: true, taken: true },
        ],
    },
    {
        id: "L2",
        label: "L2",
        instructions: ["mov eax, 1", "mov edx, 1", "jmp L3"],
        edgesOut: [{ to: "L3" }],
    },
    {
        id: "L5",
        label: "L5",
        instructions: ["mov eax, ecx"],
        edgesOut: [{ to: "L3", fallthrough: true }],
    },
    {
        id: "L3",
        label: "L3",
        instructions: [
            "sub edi, 1",
            "lea ecx, [rdx+rax]",
            "mov edx, eax",
            "cmp edi, -1",
            "jne L5",
        ],
        edgesOut: [
            { to: "L5", conditional: true, taken: true },
            { to: "L6", conditional: true, taken: false },
        ],
    },
    {
        id: "L4",
        label: "L4",
        instructions: ["mov eax, 1", "ret"],
        edgesOut: [],
    },
    {
        id: "L6",
        label: "L6",
        instructions: ["mov eax, ecx", "ret"],
        edgesOut: [],
    },
];

export const defaultCppContent = `int fib(int n) {
    int prev = 1, current = 1;
    for (; n >= 0; --n) {
        int tmp = prev + current;
        prev = current;
        current = tmp;
    }
    return current;
}`;

export const defaultAsmContent = `.globl fib
fib:
    test edi, edi
    jle .L4
    mov eax,1
    mov edx,1
.L3:
    sub edi,1
    lea ecx,[rdx+rax]
    mov edx,eax
    mov eax,ecx
    cmp edi,-1
    jne .L3
.L4:
    ret`;

export const resourceNames = [
    "HWDivider",
    "HWFPDivider",
    "HWPort0",
    "HWPort1",
    "HWPort2",
    "HWPort3",
    "HWPort4",
    "HWPort5",
    "HWPort6",
    "HWPort7",
];

export const instructionPressure: number[][] = [
  [0, 0, 0, 0.01, 0, 0, 0, 0.5, 0.5, 0],
  [0, 0, 0.01, 0.5, 0, 0, 0, 0.5, 0, 0],
  [0, 0, 0.01, 0.5, 0, 0, 0, 0, 0.5, 0],
  [0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.01, 0],
  [0, 0, 0, 0.5, 0, 0, 0, 0.01, 0.5, 0],
  [0, 0, 0.5, 0.01, 0, 0, 0, 0.5, 0, 0],
  [0, 0, 0.01, 0.5, 0, 0, 0, 0, 0.5, 0],
  [0, 0, 0.5, 0, 0, 0, 0, 0.5, 0.01, 0],
  [0, 0, 0, 0.5, 0.67, 0.67, 1.0, 0.01, 0.5, 0.67],
  [0, 0, 1.0, 0, 0, 0, 0, 0, 0.01, 0],
];

export const timelineEntries: TimelineEntry[] = [
    // Iteration 0
    {
        iteration: 0,
        instrIndex: 0,
        instrText: "movb $5, %ah",
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 1,
        instrText: "movb $5, %al",
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 2,
        instrText: "movl $6, %eax",
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 3,
        instrText: "movb $6, %al",
        dispatchCycles: [0],
        execCycles: [1],
        execEndCycles: [2],
        retireCycles: [3],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 4,
        instrText: "movb $7, %ah",
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 5,
        instrText: "movl $7, %eax",
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 6,
        instrText: "movb $8, %ah",
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 7,
        instrText: "movb $8, %al",
        dispatchCycles: [1],
        execCycles: [2],
        execEndCycles: [3],
        retireCycles: [4],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 8,
        instrText: "decl ecx",
        dispatchCycles: [1],
        execCycles: [2, 3, 4, 5, 6, 7, 8],
        execEndCycles: [9],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 0,
        instrIndex: 9,
        instrText: "jne .loop",
        dispatchCycles: [1],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [11],
        waitQueueCycles: [2, 3, 4, 5, 6, 7, 8],
        waitRetireCycles: [],
    },
    // Iteration 1
    {
        iteration: 1,
        instrIndex: 0,
        instrText: "movb $5, %ah",
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 1,
        instrText: "movb $5, %al",
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 2,
        instrText: "movl $6, %eax",
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 3,
        instrText: "movb $6, %al",
        dispatchCycles: [2],
        execCycles: [3],
        execEndCycles: [4],
        retireCycles: [10],
        waitQueueCycles: [],
        waitRetireCycles: [5, 6, 7, 8, 9],
    },
    {
        iteration: 1,
        instrIndex: 4,
        instrText: "movb $7, %ah",
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 5,
        instrText: "movl $7, %eax",
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 6,
        instrText: "movb $8, %ah",
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 7,
        instrText: "movb $8, %al",
        dispatchCycles: [3],
        execCycles: [4],
        execEndCycles: [5],
        retireCycles: [11],
        waitQueueCycles: [],
        waitRetireCycles: [6, 7, 8, 9, 10],
    },
    {
        iteration: 1,
        instrIndex: 8,
        instrText: "decl ecx",
        dispatchCycles: [4],
        execCycles: [5, 6, 7, 8, 9, 10, 11],
        execEndCycles: [12],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 1,
        instrIndex: 9,
        instrText: "jne .loop",
        dispatchCycles: [4],
        execCycles: [12],
        execEndCycles: [13],
        retireCycles: [14],
        waitQueueCycles: [5, 6, 7, 8, 9, 10, 11],
        waitRetireCycles: [],
    },
    // Iteration 2
    {
        iteration: 2,
        instrIndex: 0,
        instrText: "movb $5, %ah",
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 1,
        instrText: "movb $5, %al",
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 2,
        instrText: "movl $6, %eax",
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 3,
        instrText: "movb $6, %al",
        dispatchCycles: [5],
        execCycles: [6],
        execEndCycles: [7],
        retireCycles: [13],
        waitQueueCycles: [],
        waitRetireCycles: [8, 9, 10, 11, 12],
    },
    {
        iteration: 2,
        instrIndex: 4,
        instrText: "movb $7, %ah",
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 5,
        instrText: "movl $7, %eax",
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 6,
        instrText: "movb $8, %ah",
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 7,
        instrText: "movb $8, %al",
        dispatchCycles: [6],
        execCycles: [7],
        execEndCycles: [8],
        retireCycles: [14],
        waitQueueCycles: [],
        waitRetireCycles: [9, 10, 11, 12, 13],
    },
    {
        iteration: 2,
        instrIndex: 8,
        instrText: "decl ecx",
        dispatchCycles: [7],
        execCycles: [8, 9, 10, 11, 12, 13, 14],
        execEndCycles: [15],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 2,
        instrIndex: 9,
        instrText: "jne .loop",
        dispatchCycles: [7],
        execCycles: [15],
        execEndCycles: [16],
        retireCycles: [17],
        waitQueueCycles: [8, 9, 10, 11, 12, 13, 14],
        waitRetireCycles: [],
    },
    // Iteration 3
    {
        iteration: 3,
        instrIndex: 0,
        instrText: "movb $5, %ah",
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 1,
        instrText: "movb $5, %al",
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 2,
        instrText: "movl $6, %eax",
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 3,
        instrText: "movb $6, %al",
        dispatchCycles: [8],
        execCycles: [9],
        execEndCycles: [10],
        retireCycles: [16],
        waitQueueCycles: [],
        waitRetireCycles: [11, 12, 13, 14, 15],
    },
    {
        iteration: 3,
        instrIndex: 4,
        instrText: "movb $7, %ah",
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 5,
        instrText: "movl $7, %eax",
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 6,
        instrText: "movb $8, %ah",
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 7,
        instrText: "movb $8, %al",
        dispatchCycles: [9],
        execCycles: [10],
        execEndCycles: [11],
        retireCycles: [17],
        waitQueueCycles: [],
        waitRetireCycles: [12, 13, 14, 15, 16],
    },
    {
        iteration: 3,
        instrIndex: 8,
        instrText: "decl ecx",
        dispatchCycles: [10],
        execCycles: [11, 12, 13, 14, 15, 16, 17],
        execEndCycles: [18],
        retireCycles: [19],
        waitQueueCycles: [],
        waitRetireCycles: [],
    },
    {
        iteration: 3,
        instrIndex: 9,
        instrText: "jne .loop",
        dispatchCycles: [10],
        execCycles: [18],
        execEndCycles: [19],
        retireCycles: [20],
        waitQueueCycles: [11, 12, 13, 14, 15, 16, 17],
        waitRetireCycles: [],
    },
];
